name: no_overtime
description: "No more overtime, go home & enjoy your life"
version: 0.0.2
homepage: https://github.com/nvbien2000/no_overtime

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/holidays/
